# Generated by Django 3.0.6 on 2020-06-09 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Residue',
            fields=[
                ('Mutation', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Gene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Info.Genome')),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SDMOutcome', models.CharField(blank=True, max_length=80)),
                ('STRUMOutcome', models.CharField(blank=True, max_length=80)),
                ('mCSMOutcome', models.CharField(blank=True, max_length=80)),
                ('PredictSNPprediction', models.CharField(blank=True, max_length=80)),
                ('MAPPprediction', models.CharField(blank=True, max_length=80)),
                ('phDSNPprediction', models.CharField(blank=True, max_length=80)),
                ('PolyPhen1prediction', models.CharField(blank=True, max_length=80)),
                ('PolyPhen2prediction', models.CharField(blank=True, max_length=80)),
                ('SIFTprediction', models.CharField(blank=True, max_length=80)),
                ('SNAPprediction', models.CharField(blank=True, max_length=80)),
                ('nsSNPAnalyzerprediction', models.CharField(blank=True, max_length=80)),
                ('PANTHERprediction', models.CharField(blank=True, max_length=80)),
                ('mut', models.CharField(blank=True, max_length=80)),
                ('Mutation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info.Residue')),
            ],
        ),
    ]
