# Generated by Django 3.0.6 on 2020-06-13 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0003_remove_result_mut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='Mutation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Info.Residue'),
        ),
    ]
