# Generated by Django 3.0.6 on 2020-12-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0005_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(default='Supplementary Table', max_length=300),
            preserve_default=False,
        ),
    ]
