# Generated by Django 3.0.6 on 2021-01-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0006_files_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='users/')),
            ],
        ),
    ]
