# Generated by Django 3.0.6 on 2021-04-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0007_user_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_files',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
